name: Main
on: push

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Tar Repo
        run: |
            pwd
            ls
            tar -czf ../release.tgz --exclude="./git" .
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: "release"
          tag_name: "test_release"
          files: ../release.tgz
        
