name: Main
on: push

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@main
      
      - name: Build Libraries
        shell: bash
        run: |
          mkdir output
          mkdir output/${{ matrix.os }}
          touch output/${{ matrix.os }}/${{ matrix.os }}_ndll
          touch output/${{ matrix.os }}/${{ matrix.os }}_hash
          # zip -rv ${{ matrix.os }}_ndll.zip ../output/
          
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-ndlls
          path: output
  release:
    needs: build
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./ndlls
          merge-multiple: true
      - name: ZIP Repo
        run: |
          echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV
          zip -rv ../release.zip . -x ".git/*" ".git/**"
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: "${{ github.ref_name }}/${{ env.SHORT_SHA }}"
          tag_name: "${{ github.ref_name }}"
          files: ../release.zip
        
