name: Main
on: push

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@main
      
      - name: Build Libraries
        shell: bash
        run: |
          mkdir ../output
          touch ../output/${{ matrix.os }}_ndll
          zip -rv ${{ matrix.os }}_ndll.zip ../output/
          
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-ndlls
          path: .${{ matrix.os }}_ndll.zip
  release:
    needs: build
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ../ndlls_tmp
          merge-multiple: true
      - name: ZIP Repo
        run: |
          for f in ../tmp_artifacts/*.zip; do
            unzip -o "$f" -d ./ndlls/
            rm "$f"
          done
          zip -rv ../release.zip . -x ".git/*" ".git/**"
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: "release_3"
          tag_name: "test_release_3"
          files: ../release.zip
        
